language: python

sudo: false

matrix:
  include:
    - python: "3.5"
      env: TOX_ENV=py35-django2.0-drf3.8
    - python: "3.6"
      env: TOX_ENV=py36-django2.0-drf3.8

install:
  - pip install tox

script:
    - tox -e $TOX_ENV
