site_name: django_rest_fields_permissions
site_description: Знімок Permissions for django-rest fields
repo_url: https://github.com/AndriiPidlisnyi/django_rest_fields_permissions_package
site_dir: html
